[package]
name = "matroska"
description = "Matroska/WebM demuxer"
version = "0.1.0"
authors = ["Luca Barbato <lu_zero@gentoo.org>"]
readme = "README.md"
license = "MIT"

[dependencies]
nom = { git = "https://github.com/Geal/nom", branch="result" }
cookie-factory = "^0.2"
av-format = {git = "https://github.com/rust-av/rust-av" }
av-data = {git = "https://github.com/rust-av/rust-av" }

[dev-dependencies]
quickcheck = "0.3"
