[package]
name = "matroska"
description = "Matroska/WebM demuxer"
version = "0.1.0"
authors = ["Luca Barbato <lu_zero@gentoo.org>"]
readme = "README.md"
license = "MIT"

[dependencies]
nom = { git = "https://github.com/Geal/nom", branch="result" }
cookie-factory = "^0.2"
av-data = { version = "0.1.0", path = "../rust-av/data" }
av-format = { version = "0.1.0", path = "../rust-av/format" }

[dev-dependencies]
quickcheck = "0.3"
